version: 2

sources:
  - name: sh_database
    schema: sh
    quoting:
        database: false
        schema: false
        identifier: false
    tables:
      - name: customers
      - name: sales
        freshness: # default freshness
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: time_id
      - name: products
      - name: times
      - name: channels
      - name: countries
      - name: promotions
      - name: costs

models:
  - name: sales_internet_mv
    description: Test comment for Materialized View

  - name: kafka
    description: kafka_description
    config:
      materialized: incremental
      incremental_strategy: append
      on_schema_change: fail
      full_refresh: false
      contract:
        enforced: true
      constraints:
        - type: not_null
          columns: [message]
    columns:
      - name: message
        description: Kafka message
        data_type: CLOB
        constraints:
          - type: not_null
      - name: blob_message
        description: Kafka message
        data_type: BLOB
        constraints:
          - type: not_null


  - name: people
    columns:
      - name: id
        tests:
          - dbt_constraints.primary_key
          - not_null
          - unique
      - name: gender
        tests:
          - accepted_values:
              values: ['Male', 'Female']
  - name: countries
    columns:
      - name: country_id
        tests:
          - dbt_constraints.primary_key
          - not_null
          - unique
  - name: eu_direct_sales_channels_promo_costs
    columns:
      - name: country_id
        tests:
          - relationships:
              to: ref('countries')
              field: country_id
          - dbt_constraints.foreign_key:
              pk_table_name: ref('countries')
              pk_column_name: country_id


